# Generated by Django 5.0.13 on 2025-04-11 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0004_transaction_trades_tran_user_id_e9afa0_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="trans_type",
            field=models.CharField(
                choices=[
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Instant Buy", "Instant Buy"),
                    ("Instant Sell", "Instant Sell"),
                    ("Placing Buy", "Placing Buy"),
                    ("Placing Sell", "Placing Sell"),
                ],
                default="Buy",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ban_until", models.DateTimeField(blank=True, null=True)),
                ("permanent", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
