# Generated by Django 5.0.13 on 2025-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0005_alter_transaction_trans_type_userban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="trans_type",
            field=models.CharField(
                choices=[
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Instant Buy", "Instant Buy"),
                    ("Instant Sell", "Instant Sell"),
                    ("Placing Buy", "Placing Buy"),
                    ("Placing Sell", "Placing Sell"),
                ],
                default="Buy",
                max_length=25,
            ),
        ),
    ]
