# Generated by Django 5.0.13 on 2025-04-11 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0006_alter_transaction_trans_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date_of_holding",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
